// Vorschlagslisten für die Katzen-Verwaltung (Settings) — reine UI-Hilfe,
// keine Validierung: Freitext bleibt über "Andere" weiterhin möglich.

export const CAT_TAG_SUGGESTIONS = [
  'indoor',
  'outdoor',
  'sensibel',
  'verschmust',
  'scheu',
  'verspielt',
  'ruhig',
  'chronisch krank',
  'übergewichtig',
  'senior',
  'kastriert',
  'allergiker',
  'ängstlich',
  'dominant',
  'neu im Haushalt',
] as const

// Alphabetisch sortiert, "Andere" immer am Ende (Freitext-Fallback statt Rasse).
export const CAT_BREEDS = [
  'Abessinier',
  'American Shorthair',
  'Balinese',
  'Bengalkatze',
  'Birma',
  'Bombay',
  'Britisch Kurzhaar',
  'Burmese',
  'Chartreux',
  'Cornish Rex',
  'Devon Rex',
  'Egyptian Mau',
  'Exotic Shorthair',
  'Hauskatze / Mischling',
  'Himalaya',
  'Japanese Bobtail',
  'Korat',
  'Maine Coon',
  'Manx',
  'Munchkin',
  'Norwegische Waldkatze',
  'Ocicat',
  'Perserkatze',
  'Ragdoll',
  'Russisch Blau',
  'Savannah',
  'Scottish Fold',
  'Siamkatze',
  'Singapura',
  'Snowshoe',
  'Somali',
  'Sphynx',
  'Tonkanese',
  'Türkisch Angora',
  'Andere',
] as const
